global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'springboot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springboot:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
