services:
  mysql:
    image: mysql:8.0
    container_name: dingdong-local-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "dingdong"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: