services:
  app:
    image: shortboy710/dingdong:latest
    container_name: dingdong
    build:
      context: ..
      dockerfile: ./.deploy/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.example
    volumes:
      - ./key:/app/key