name: Sync Organization Branch to Personal Repo

on:
  push:
    branches:
      - frontend # 조직의 frontend 브랜치 변경 시 실행

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Organization Repo
        uses: actions/checkout@v3
        with:
          repository: softeer5th/team1-dingdong
          ref: frontend # 조직의 frontend 브랜치 가져오기

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Personal Repository as Remote
        run: |
          git remote add personal https://x-access-token:${{ secrets.CLASSIC_PERSONAL_ACCESS_TOKEN }}@github.com/vavoya/ding-dong.git
          git fetch personal main || true # 내 저장소의 main 브랜치 가져오기
          git checkout -b sync-upstream personal/main || git checkout sync-upstream
          git merge --no-edit frontend # 조직의 최신 코드와 병합
          git push personal sync-upstream --force # 내 저장소에 강제 푸시

      - name: Create Pull Request in Personal Repository
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.CLASSIC_PERSONAL_ACCESS_TOKEN }}
          commit-message: "🔄 Sync from Organization Repository"
          branch: sync-upstream
          delete-branch: true
          base: main
          title: "🔄 Sync from Organization Repository"
          body: "조직 저장소에서 최신 변경 사항을 가져왔습니다."

      - name: Auto Merge Pull Request in Personal Repository
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.CLASSIC_PERSONAL_ACCESS_TOKEN }}
        with:
          mergeMethod: merge
          approve: true
          deleteBranchAfterMerge: true
